// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnSKqHeVnPsGlCZxFh6Pd-2XbObmkBl-I',
    appId: '1:830630970733:web:8e799c3176da069e204664',
    messagingSenderId: '830630970733',
    projectId: 'firechat-15f95',
    authDomain: 'firechat-15f95.firebaseapp.com',
    databaseURL: 'https://firechat-15f95.firebaseio.com',
    storageBucket: 'firechat-15f95.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfpemGpY4xObn_aaSfLsic5_Zzge5v018',
    appId: '1:830630970733:android:20097a927b7e4556204664',
    messagingSenderId: '830630970733',
    projectId: 'firechat-15f95',
    databaseURL: 'https://firechat-15f95.firebaseio.com',
    storageBucket: 'firechat-15f95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMW8rsnv1wLwD30jpoKDxsniYUG0OiIYo',
    appId: '1:830630970733:ios:3fa6262075ffae5f204664',
    messagingSenderId: '830630970733',
    projectId: 'firechat-15f95',
    databaseURL: 'https://firechat-15f95.firebaseio.com',
    storageBucket: 'firechat-15f95.appspot.com',
    iosClientId: '830630970733-5jme4lcejdpahta5nedonb2qddgiq249.apps.googleusercontent.com',
    iosBundleId: 'com.example.balanceApp',
  );
}
